Update action_on_demand.yml

diff --git a/.github/workflows/action_on_demand.yml b/.github/workflows/action_on_demand.yml
--- a/.github/workflows/action_on_demand.yml
+++ b/.github/workflows/action_on_demand.yml
@@ -4,24 +4,52 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
+  prepare:
     runs-on: ubuntu-latest
-   
-    container: 
-      image: hkershaw/dart-dep:1.0
-      options: "--cap-add=SYS_PTRACE"
+    # Using a matrix (JSON array) to run the 'build' job in parallel for each quickbuild.sh script
+
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+      # Outputs the matrix for the 'build' job
 
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
-        with:
-          repository: 'NCAR/DART'
-          ref: ${{ github.event.inputs.branch }}
-      
+
+      - name: Find all quickbuild.sh scripts
+        id: set-matrix
+        run: |
+          scripts=$(find $GITHUB_WORKSPACE -executable -type f -name 'quickbuild.sh' | jq -R -s -c 'split("\n")[:-1]')
+          echo "scripts=$scripts" >> $GITHUB_ENV
+          echo "::set-output name=matrix::$scripts"
+          echo "Matrix: $scripts"
+          # format all quickbuild.sh scripts as JSON array
+          # replace set-output command with new Environment Files method
+
+  build:
+    needs: prepare
+    runs-on: ubuntu-latest
+    strategy:
+      matrix: 
+        script: ${{ fromJson(needs.prepare.outputs.matrix) }}
+      # Matrix strategy that will run 'build' job in parallel
+
+    container: 
+      image: hkershaw/dart-dep:1.0
+      options: "--cap-add=SYS_PTRACE"
+      # Docker container (need new one for RTTOV)
+
+    steps:
+      - name: re-checkout repo
+        uses: actions/checkout@v4
+
+      - name: Set to safe directory
+        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
+
       - name: Create mkmf.template
         run: |
-          # echo "RTTOV version ${{ github.event.inputs.rttov_version }}"
           cp build_templates/mkmf.template.gfortran build_templates/mkmf.template
+          # Copy gfortran mkmf.template only
 
       - name: Run fixsystem
         run: |
@@ -29,24 +57,25 @@ jobs:
           cd $DART/assimilation_code/modules/utilities
           ./fixsystem gfortran
           cd -
+          # Run fixsystem once
 
       - name: Modify input.nml files
         run: |
           find $DART -name input.nml -exec sed -i -e "/^[[:space:]]*#/! s|.*output_obs_def_mod_file.*|output_obs_def_mod_file = './obs_def_mod.f90'|g" \
             -e "/^[[:space:]]*#/! s|.*output_obs_qty_mod_file.*|output_obs_qty_mod_file = './obs_kind_mod.f90'|g" \
             -e "/^[[:space:]]*#/! s|.*output_obs_kind_mod_file.*|output_obs_qty_mod_file = './obs_kind_mod.f90'|g" {} \;
+          # update input.nm files to avoid race conditions when running preprocess
 
       - name: Run quickbuild.sh scripts
         run: |
-          find $DART -executable -type f -name quickbuild.sh | while read qb; do
-            (cd "$(dirname "$qb")" && ./quickbuild.sh) || echo "FAILED: $qb" >> $GITHUB_WORKSPACE/quickbuild-failures.txt
-          done
-      
+          cd "$(dirname "${{ matrix.script }}")"
+          ./quickbuild.sh || echo "FAILED: ${{ matrix.script }}" >> $GITHUB_WORKSPACE/quickbuild-failures.txt
+          # Run quickbuild.sh scripts and log failures
+
       - name: Report Failures
+        if: failure()
         run: |
-          if [ -f $GITHUB_WORKSPACE/quickbuild-failures.txt ]; then
-            echo "Failed builds:"
-            cat $GITHUB_WORKSPACE/quickbuild-failures.txt
-            exit 1
-          else
-            echo "All runs passed"
+          echo "Fails:"
+          cat $GITHUB_WORKSPACE/quickbuild-failures.txt
+          exit 1
+          # Report all failed runs
